version: 2
updates:
  - package-ecosystem: gomod
    directory: /fiveserver-go
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /flask-web
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
